title: Ваше имя
description: Ваше описание
baseurl: ""  # Для username.github.io оставьте пустым
url: "https://mikrobic.github.io"  # Ваш URL

# Важные настройки
theme: beautiful-jekyll-theme
remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Информация о вас
avatar: assets/img/avatar.jpg
social:
  github: Mikrobic
