title: Ваш сайт
description: Описание сайта
baseurl: "/sites"  # Для project sites
url: "https://mikrobic.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
