title: OkulusDev
description: Блог о разработке и IT
baseurl: "/sites"
url: "https://mikrobic.github.io"
theme: minima

# Настройки
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Автор
author:
  name: Okulus
  email: your@email.com
  github: okulusdev
  twitter: yourtwitter

# Настройки сборки
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
