title: Мой потрясающий сайт
description: Личный блог и портфолио
theme: jekyll-theme-cayman  # Можно использовать другую тему
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройки URL
url: "https://username.github.io"
baseurl: ""

# Соцсети (опционально)
twitter_username: yourtwitter
github_username: yourgithub
