title: Mikrobic Sites
description: Мой сайт-портфолио
baseurl: "" # Оставьте пустым для репозитория sites
url: "https://mikrobic.github.io"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
