title: Mikrobic Sites
description: Профессиональный сайт-портфолио
baseurl: "/sites"
url: "https://mikrobic.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
