title: Ваш сайт
description: Описание сайта
baseurl: "/sites"  # Для project site
url: "https://mikrobic.github.io"

remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Дополнительные настройки Beautiful Jekyll
avatar: assets/img/avatar.jpg
social:
  github: Mikrobic
